ModuleIdentifier = "82a1b924-415b-4600-bd00-7651e1216eb9"
PackageName = "GeneXusUnanimo"
ModuleVersion = "2.0.194"
ModuleDescription = "General purpose Design System and related building blocks designed by GeneXus for the GeneXus Community"
ModuleAuthor = "GeneXus"
ModuleLicenseUrl = "https://www.apache.org/licenses/LICENSE-2.0.txt"
ModuleProjectUrl = "https://wiki.genexus.com/commwiki/wiki?48382,Unanimo"
ModuleServerUrl = "https://samples.genexusserver.com/beta/kbdashboard.aspx?Unanimo,"
ModuleTags = "DS, Design System"
ModuleOwner = "GeneXus"
Name = "GeneXusUnanimo"
Description = "GeneXus Unanimo"
IsDefault = "False"
