ModuleIdentifier = "4f454e73-7d8f-4a0f-908a-1a355f3634a5"
PackageName = "GeneXus"
ModuleVersion = "4.15.53"
ModuleDescription = "GeneXus Core Module is a basic set of interfaces and implementations of data structures and algorithms to solve common programming use cases."
ModuleAuthor = "GeneXus"
ModuleOwner = "GeneXus"
Name = "GeneXus"
Description = "GeneXus Core Modules"
IsDefault = "False"
